import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import moment from "moment";
import "moment/locale/pt-br";
import { HomeIcon, LogOutIcon } from "lucide-react";
import Providers from "./providers";
moment.locale("pt-br");

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="flex h-[100vh] w-[100vw] ">
            <div className="w-14 h-full overflow-hidden flex flex-col  text-primary items-center border-r-2">
              <div className="size-14 flex items-center justify-center border-b">
                <p>Logo</p>
              </div>

              <div className="w-full py-3 flex justify-center cursor-pointer hover:bg-primary hover:text-neutral-50 transition-all">
                <HomeIcon />
              </div>

              <div className="w-full py-3 flex justify-center mt-auto cursor-pointer hover:bg-primary hover:text-neutral-50 transition-all">
                <LogOutIcon />
              </div>
            </div>
            <div className="flex-1 flex flex-col px-6 py-4">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
